Fix/mvp2 677
wallfair-organization/trading-engine pull request #29
Opened 2021-11-25 17:58 UTC by fan711

Small fixes as discussed in #28 which as already merged.

2021-11-29 08:40 UTC, SamirHodzic commented on src/test/transaction-manager.spec.ts
> +import { initDb } from "../lib/main";
Please be consistent with quotes and use single one. Probably linter fix already did that for you locally, but you didn't commit.

2021-11-29 14:45 UTC, zametica requested changes

2021-11-29 14:45 UTC, zametica commented on src/lib/main.ts
> +export const initDb = async (dbConfig = null) => {
why do we need this argument here?

2021-11-29 14:45 UTC, zametica commented on src/lib/main.ts
> +export const closeAllConnections = async () => {
any case where you'd need to use this?

2021-11-29 14:45 UTC, zametica commented on src/test/account.spec.ts
> +  connection = await initDb(config);
why? if you need to test it you can create a test for `initDb`, but I don't see any reason for testing it, you would test typeorm's method basically. usually test setups should not work with implemented methods

2021-11-29 14:49 UTC, fan711 commented on src/lib/main.ts
> +export const initDb = async (dbConfig = null) => {
In case any code using trading-engine needs to pass specific connection configuration. It is not actively used yet though and could as well be removed.

2021-11-29 14:54 UTC, zametica commented on src/lib/main.ts
> +export const initDb = async (dbConfig = null) => {
nope, we're not working with db connection config here, it's orm config where you have all different paths for entities, migrations etc. we need to make sure those match the codebase and structure in the lib. client is not the one taking care of that.

2021-12-01 10:22 UTC, SamirHodzic commented
Closing per obsolete and discussion.

2021-12-01 10:22 UTC, closed without merging