- extend pg pool config
wallfair-organization/trading-engine pull request #58
Opened 2021-12-20 20:32 UTC by SamirHodzic

2021-12-20 20:39 UTC, haris-bravo-klika approved these changes

2021-12-21 08:03 UTC, rudolfix requested changes

2021-12-21 08:03 UTC, rudolfix commented on src/db/config.ts
> +    idleTimeoutMillis: +process.env.POOL_IDLE_TIMEOUT || 30000,
also `connectionTimeoutMillis` is not set. this tells how long to wait for a free connection in the pool. I do not think we should wait longer than 1s.

maybe we shoudl also set this? `query_timeout` 1s should be enough for everything that is in transactions

2021-12-21 08:41 UTC, SamirHodzic commented on src/db/config.ts
> +    idleTimeoutMillis: +process.env.POOL_IDLE_TIMEOUT || 30000,
Just set `idleTimeoutMillis` value as placeholder, we will have postgres config secret globally with 10s.

Added `connectionTimeoutMillis` with 1s.

`query_timeout` does not exist on underlaying pg-pool driver. (https://github.com/brianc/node-postgres/tree/master/packages/pg-pool#use)

2021-12-21 10:20 UTC, rudolfix approved these changes

2021-12-21 12:24 UTC, merged